---
- name: Install DHCP server
  apt:
    name: "{{ dhcp_server_packages }}"
    state: present
    update_cache: yes
  tags: dhcp

- name: Configure Kea DHCPv4 server
  template:
    src: kea-dhcp4.conf.j2
    dest: "{{ dhcp_config_path }}"
    owner: root
    group: root
    mode: "0644"
    validate: "kea-dhcp4 -t %s"
  notify: Restart DHCP Service
  tags: dhcp

- name: Enable and start DHCP service
  service:
    name: "{{ dhcp_service_name }}"
    enabled: true
    state: started
  tags: dhcp
