---
- name: Restart Postfix Service
  service:
    name: "{{ mail_postfix_service_name }}"
    state: restarted

- name: Restart Dovecot Service
  service:
    name: "{{ mail_dovecot_service_name }}"
    state: restarted
