---
- name: Configure LKS server
  hosts: lks
  become: true
  gather_facts: true

  roles:
    - role: firewall
      tags: firewall
    - role: dns
      tags: dns
    - role: dhcp
      tags: dhcp
    - role: web
      tags: web
    - role: ldap
      tags: ldap
    - role: nfs
      tags: nfs
    - role: mail
      tags: mail
    - role: vpn
      tags: vpn
    - role: test
      tags: test
